### PR TITLE
Handling WalletConnectProvider.request

### PR DESCRIPTION
**Pull request by Velenir**
Multiple hackarounds later it works
But needs more testing

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1245--dexreact.review.gnosisdev.com

**Comment by alfetopito** [comment]
Err well. It killed my browser. I'll refrain from testing for now :sweat_smile:

**Comment by Velenir** [comment]
> Err well. It killed my browser. I'll refrain from testing for now

How? Why? :hocho:? :gun: ?

**Comment by alfetopito** [comment]
> > Err well. It killed my browser. I'll refrain from testing for now
> 
> How? Why? hocho? gun ?

Not sure. Page with console open, suuuuper slow to update things in the ui like orders. After awhile of waiting the whole browser just gave up and went away =P
Possibly too many logs for my machine to handle?

**Comment by Velenir** [comment]
> > > Err well. It killed my browser. I'll refrain from testing for now
> > 
> > 
> > How? Why? hocho? gun ?
> 
> Not sure. Page with console open, suuuuper slow to update things in the ui like orders. After awhile of waiting the whole browser just gave up and went away =P
> Possibly too many logs for my machine to handle?

I disabled most logs
Can you try again. In production should be even less logs.

**Comment by Velenir** [comment]
@anxolin, can you check once more what happens in iOS
there's been a substantial WC update

also would be cool if anyone else tested again with different WC wallets
Argent and Safe work

**Comment by anxolin** [comment]
bad bot, don't close

**Comment by Velenir** [comment]
> bad bot, don't close

Oh my,i t almost happened, and I didn't notice

**Comment by anxolin** [comment]
Superseded by https://github.com/gnosis/gp-ui/pull/9

**Pull request closed without merging**
